export type Publication = {
  id: number;
  title: string;
  authors: string;
  year: number;
  journal: string;
  imageUrl: string;
  aiHint: string;
  pdfUrl: string;
  fullTextUrl?: string;
  doi?: string;
  abstract: string;
  cites: number;
  citesPerYear: number;
  slug: string;
  tags: string[];
};

function createSlug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^\w\s-]/g, "")
    .replace(/[\s_-]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function extractTags(title: string, journal: string): string[] {
  const tags: string[] = [];
  const t = title.toLowerCase();
  const j = journal.toLowerCase();
  if (j.includes("lancet")) tags.push("The Lancet");
  if (j.includes("nejm") || j.includes("new england")) tags.push("NEJM");
  if (j.includes("jama")) tags.push("JAMA");
  if (j.includes("plos")) tags.push("PLoS");
  if (j.includes("bmj")) tags.push("BMJ");
  if (j.includes("bmc")) tags.push("BMC");
  if (t.includes("covid") || j.includes("covid")) tags.push("COVID-19");
  if (t.includes("hiv") || j.includes("hiv") || t.includes("aids")) tags.push("HIV/AIDS");
  if (t.includes("antiretroviral") || t.includes("art")) tags.push("Antiretroviral Therapy");
  if (t.includes("fluvoxamine")) tags.push("Fluvoxamine");
  if (t.includes("ivermectin")) tags.push("Ivermectin");
  if (t.includes("hydroxychloroquine")) tags.push("Hydroxychloroquine");
  if (t.includes("metformin")) tags.push("Metformin");
  if (t.includes("interferon")) tags.push("Interferon");
  if (t.includes("rwanda")) tags.push("Rwanda");
  if (t.includes("uganda")) tags.push("Uganda");
  if (t.includes("africa")) tags.push("Africa");
  if (t.includes("together")) tags.push("TOGETHER Trial");
  if (t.includes("meta-analysis") || t.includes("meta analysis")) tags.push("Meta-analysis");
  if (t.includes("systematic review")) tags.push("Systematic Review");
  if (t.includes("msm") || t.includes("men who have sex with men") || t.includes("gay")) tags.push("MSM Health");
  if (t.includes("adherence")) tags.push("Adherence");
  if (t.includes("stigma")) tags.push("Stigma");
  const unique = [...new Set(tags)];
  return unique.length > 0 ? unique : ["Global Health"];
}

export const publications: Publication[] = [
  {
    id: 1,
    title: "Effect of spirulina on risk of hospitalization among patients with COVID-19: the TOGETHER randomized trial",
    authors: "G Reis, EASM Silva, DCM Silva, L Thabane, ...",
    year: 2024,
    journal: "The American Journal of …",
    imageUrl: "/pdf/thumbnails/Reis-2024-Effect of spirulina on risk of hospi.png",
    aiHint: "",
    pdfUrl: "/pdf/Reis-2024-Effect of spirulina on risk of hospi.pdf",
    fullTextUrl: "https://ajcn.nutrition.org/article/S0002-9165(24)00588-4/pdf",
    abstract: "Background Algae-derived nutraceuticals, such as spirulina, have been reported to have biological activities that may minimize clinical consequences to COVID-19 infections …",
    cites: 1,
    citesPerYear: 1.0,
    slug: createSlug("Effect of spirulina on risk of hospitalization among patients with COVID-19: the TOGETHER randomized trial"),
    tags: extractTags("Effect of spirulina on risk of hospitalization among patients with COVID-19: the TOGETHER randomized trial", "The American Journal of …"),
  },
  {
    id: 2,
    title: "Matched vs Nonmatched Placebos in a Randomized Trial of COVID-19 Treatments",
    authors: "G Reis, LCM Savassi, TS Ferreira, LLF Reis, ...",
    year: 2024,
    journal: "JAMA Network …",
    imageUrl: "/images/contrasting-innovations.png",
    aiHint: "",
    pdfUrl: "/pdf/Matched vs Nonmatched Placebos in a Randomized Trial of COVID-19 Treatments.pdf",
    fullTextUrl: "https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2818862",
    abstract: "Importance Matched placebo interventions are complex and resource intensive. Recent evidence suggests matched placebos may not always be necessary. Previous studies have …",
    cites: 0,
    citesPerYear: 0.0,
    slug: createSlug("Matched vs Nonmatched Placebos in a Randomized Trial of COVID-19 Treatments"),
    tags: extractTags("Matched vs Nonmatched Placebos in a Randomized Trial of COVID-19 Treatments", "JAMA Network …"),
  },
  {
    id: 3,
    title: "Early treatment with pegylated interferon lambda for Covid-19",
    authors: "G Reis, EAS Moreira Silva, ...",
    year: 2023,
    journal: "… England Journal of …",
    imageUrl: "/images/contrasting-innovations.png",
    aiHint: "",
    pdfUrl: "https://www.nejm.org/doi/full/10.1056/NEJMoa2209760",
    doi: "10.1056/NEJMoa2209760",
    abstract: "Background The efficacy of a single dose of pegylated interferon lambda in preventing clinical events among outpatients with acute symptomatic coronavirus disease 2019 (Covid …",
    cites: 174,
    citesPerYear: 87.0,
    slug: createSlug("Early treatment with pegylated interferon lambda for Covid-19"),
    tags: extractTags("Early treatment with pegylated interferon lambda for Covid-19", "… England Journal of …"),
  },
  {
    id: 4,
    title: "Oral fluvoxamine with inhaled budesonide for treatment of early-onset COVID-19: a randomized platform trial",
    authors: "G Reis, EA dos Santos Moreira Silva, ...",
    year: 2023,
    journal: "Annals of internal …",
    imageUrl: "/pdf/thumbnails/Reis-2023-Oral Fluvoxamine With Inhaled Budeso.png",
    aiHint: "",
    pdfUrl: "/pdf/Reis-2023-Oral Fluvoxamine With Inhaled Budeso.pdf",
    fullTextUrl: "https://www.acpjournals.org/doi/pdf/10.7326/M22-3305?download=true",
    doi: "10.7326/M22-3305",
    abstract: "Background: Previous trials have demonstrated the effects of fluvoxamine alone and inhaled budesonide alone for prevention of disease progression among outpatients with COVID-19 …",
    cites: 34,
    citesPerYear: 17.0,
    slug: createSlug("Oral fluvoxamine with inhaled budesonide for treatment of early-onset COVID-19: a randomized platform trial"),
    tags: extractTags("Oral fluvoxamine with inhaled budesonide for treatment of early-onset COVID-19: a randomized platform trial", "Annals of internal …"),
  },
  {
    id: 5,
    title: "Effect of early treatment with fluvoxamine on risk of emergency care and hospitalisation among patients with COVID-19: the TOGETHER randomised, platform …",
    authors: "G Reis, EA dos Santos Moreira-Silva, ...",
    year: 2022,
    journal: "The Lancet Global …",
    imageUrl: "/images/contrasting-innovations.png",
    aiHint: "",
    pdfUrl: "https://www.thelancet.com/journals/langlo/article/PIIS2214-109X(21)00448-4/fulltext?mst-click=yes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes%3Fmst-click%3Dyes",
    abstract: "Background Recent evidence indicates a potential therapeutic role of fluvoxamine for COVID-19. In the TOGETHER trial for acutely symptomatic patients with COVID-19, we …",
    cites: 415,
    citesPerYear: 138.33,
    slug: createSlug("Effect of early treatment with fluvoxamine on risk of emergency care and hospitalisation among patients with COVID-19: the TOGETHER randomised, platform …"),
    tags: extractTags("Effect of early treatment with fluvoxamine on risk of emergency care and hospitalisation among patients with COVID-19: the TOGETHER randomised, platform …", "The Lancet Global …"),
  },
  {
    id: 6,
    title: "Effect of early treatment with ivermectin among patients with Covid-19",
    authors: "G Reis, EASM Silva, DCM Silva, ...",
    year: 2022,
    journal: "… England Journal of …",
    imageUrl: "/images/contrasting-innovations.png",
    aiHint: "",
    pdfUrl: "https://www.nejm.org/doi/pdf/10.1056/nejmoa2115869",
    doi: "10.1056/NEJMoa2115869",
    abstract: "Background The efficacy of ivermectin in preventing hospitalization or extended observation in an emergency setting among outpatients with acutely symptomatic coronavirus disease …",
    cites: 264,
    citesPerYear: 88.0,
    slug: createSlug("Effect of early treatment with ivermectin among patients with Covid-19"),
    tags: extractTags("Effect of early treatment with ivermectin among patients with Covid-19", "… England Journal of …"),
  },
  {
    id: 7,
    title: "Effect of early treatment with metformin on risk of emergency care and hospitalization among patients with COVID-19: The TOGETHER randomized platform …",
    authors: "G Reis, EASM Silva, DCM Silva, L Thabane, ...",
    year: 2022,
    journal: "The Lancet Regional …",
    imageUrl: "/images/contrasting-innovations.png",
    aiHint: "",
    pdfUrl: "https://www.thelancet.com/journals/lanam/article/PIIS2667-193X(21)00138-1/fulltext?uuid=uuid%3A2ff97f32-4308-4a3f-8ec2-b4778b5e8a32",
    abstract: "Background Observational studies have postulated a therapeutic role of metformin in treating COVID-19. We conducted an adaptive platform clinical trial to determine whether …",
    cites: 63,
    citesPerYear: 21.0,
    slug: createSlug("Effect of early treatment with metformin on risk of emergency care and hospitalization among patients with COVID-19: The TOGETHER randomized platform …"),
    tags: extractTags("Effect of early treatment with metformin on risk of emergency care and hospitalization among patients with COVID-19: The TOGETHER randomized platform …", "The Lancet Regional …"),
  },
  {
    id: 8,
    title: "Interferon treatments for SARS-CoV-2: challenges and opportunities",
    authors: "D Jhuti, A Rawat, CM Guo, LA Wilson, EJ Mills, ...",
    year: 2022,
    journal: "Infectious diseases and …",
    imageUrl: "/pdf/thumbnails/Jhuti-2022-Interferon Treatments for SARS-CoV-.png",
    aiHint: "",
    pdfUrl: "/pdf/Jhuti-2022-Interferon Treatments for SARS-CoV-.pdf",
    fullTextUrl: "https://link.springer.com/article/10.1007/s40121-022-00633-9",
    doi: "10.1007/s40121-022-00633-9",
    abstract: "Interferon (IFN) therapies are used to treat a variety of infections and diseases and could be used to treat SARS-CoV-2. However, optimal use and timing of IFN therapy to treat SARS …",
    cites: 36,
    citesPerYear: 12.0,
    slug: createSlug("Interferon treatments for SARS-CoV-2: challenges and opportunities"),
    tags: extractTags("Interferon treatments for SARS-CoV-2: challenges and opportunities", "Infectious diseases and …"),
  },
  {
    id: 9,
    title: "Fluvoxamine for the early treatment of COVID-19: a meta-analysis of randomized clinical trials",
    authors: "CM Guo, O Harari, C Chernecki, ...",
    year: 2022,
    journal: "… American Journal of …",
    imageUrl: "/images/contrasting-innovations.png",
    aiHint: "",
    pdfUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC9128689/",
    abstract: "Fluvoxamine is widely prescribed as an antidepressant. Recent studies show the drug may have a clinical benefit in treating COVID-19. We aimed to perform a meta-analysis of the …",
    cites: 21,
    citesPerYear: 7.0,
    slug: createSlug("Fluvoxamine for the early treatment of COVID-19: a meta-analysis of randomized clinical trials"),
    tags: extractTags("Fluvoxamine for the early treatment of COVID-19: a meta-analysis of randomized clinical trials", "… American Journal of …"),
  },
  {
    id: 10,
    title: "Early treatment with fluvoxamine among patients with COVID-19: a cost-consequence model",
    authors: "FP Mills, G Reis, LA Wilson, K Thorlund, ...",
    year: 2022,
    journal: "… American Journal of …",
    imageUrl: "/pdf/thumbnails/Mills-2023-Early Treatment with Fluvoxamine am.png",
    aiHint: "",
    pdfUrl: "/pdf/Mills-2023-Early Treatment with Fluvoxamine am.pdf",
    fullTextUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC9833089/",
    abstract: "To date, two published randomized trials have indicated a clinical benefit of early treatment with fluvoxamine versus placebo for adults with symptomatic COVID-19. Using the results of …",
    cites: 6,
    citesPerYear: 2.0,
    slug: createSlug("Early treatment with fluvoxamine among patients with COVID-19: a cost-consequence model"),
    tags: extractTags("Early treatment with fluvoxamine among patients with COVID-19: a cost-consequence model", "… American Journal of …"),
  },
  {
    id: 11,
    title: "Brief report: Active HIV case finding in the city of Kigali, Rwanda: Assessment of voluntary assisted partner notification modalities to detect undiagnosed HIV …",
    authors: "E Remera, S Nsanzimana, F Chammartin, ...",
    year: 2022,
    journal: "JAIDS Journal of …",
    imageUrl: "/images/double-helix.png",
    aiHint: "",
    pdfUrl: "https://journals.lww.com/jaids/fulltext/2022/04010/brief_report__active_hiv_case_finding_in_the_city.9.aspx",
    abstract: "Background: Voluntary assisted partner notification (VAPN) services that use contract, provider, or dual referral modalities may be efficient to identify individuals with undiagnosed …",
    cites: 6,
    citesPerYear: 2.0,
    slug: createSlug("Brief report: Active HIV case finding in the city of Kigali, Rwanda: Assessment of voluntary assisted partner notification modalities to detect undiagnosed HIV …"),
    tags: extractTags("Brief report: Active HIV case finding in the city of Kigali, Rwanda: Assessment of voluntary assisted partner notification modalities to detect undiagnosed HIV …", "JAIDS Journal of …"),
  },
  {
    id: 12,
    title: "Toward a New Paradigm of North–South and South–South Partnerships for Pandemic Preparedness: Lessons Learned from COVID-19 and Other Outbreaks",
    authors: "S Nsanzimana, A Rawat, LA Wilson, ...",
    year: 2022,
    journal: "… American Journal of …",
    imageUrl: "/pdf/thumbnails/Nsanzimana-2022-Toward a New Paradigm of North.png",
    aiHint: "",
    pdfUrl: "/pdf/Nsanzimana-2022-Toward a New Paradigm of North.pdf",
    fullTextUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC9768281/",
    abstract: "COVID-19 underscores the need to reimagine North–South partnerships and redefine best practices for building public health and research capacity to address emergent health …",
    cites: 6,
    citesPerYear: 2.0,
    slug: createSlug("Toward a New Paradigm of North–South and South–South Partnerships for Pandemic Preparedness: Lessons Learned from COVID-19 and Other Outbreaks"),
    tags: extractTags("Toward a New Paradigm of North–South and South–South Partnerships for Pandemic Preparedness: Lessons Learned from COVID-19 and Other Outbreaks", "… American Journal of …"),
  },
  {
    id: 13,
    title: "Factors associated with recent HIV infections among newly HIV diagnosed in Rwanda.",
    authors: "E Remera, F Chammartin, S Nsanzimana, ...",
    year: 2022,
    journal: "JAIDS Journal of …",
    imageUrl: "/images/double-helix.png",
    aiHint: "",
    pdfUrl: "https://journals.lww.com/jaids/_layouts/15/oaks.journals/downloadpdf.aspx?an=00126334-990000000-00616",
    abstract: "Methods: We included all newly diagnosed HIV patients aged 15 and above who consented to recency testing and assessed patient and health center related predictors of recent HIV …",
    cites: 0,
    citesPerYear: 0.0,
    slug: createSlug("Factors associated with recent HIV infections among newly HIV diagnosed in Rwanda."),
    tags: extractTags("Factors associated with recent HIV infections among newly HIV diagnosed in Rwanda.", "JAIDS Journal of …"),
  },
  {
    id: 14,
    title: "Effect of early treatment with hydroxychloroquine or lopinavir and ritonavir on risk of hospitalization among patients with COVID-19: the TOGETHER randomized …",
    authors: "G Reis, EASM Silva, DCM Silva, L Thabane, ...",
    year: 2021,
    journal: "JAMA Network …",
    imageUrl: "/pdf/thumbnails/Reis-2021-Effect of Early Treatment With Hydro.png",
    aiHint: "",
    pdfUrl: "/pdf/Reis-2021-Effect of Early Treatment With Hydro.pdf",
    fullTextUrl: "https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2779044",
    abstract: "Importance Data on the efficacy of hydroxychloroquine or lopinavir-ritonavir for the treatment of high-risk outpatients with COVID-19 in developing countries are needed. Objective To …",
    cites: 165,
    citesPerYear: 41.25,
    slug: createSlug("Effect of early treatment with hydroxychloroquine or lopinavir and ritonavir on risk of hospitalization among patients with COVID-19: the TOGETHER randomized …"),
    tags: extractTags("Effect of early treatment with hydroxychloroquine or lopinavir and ritonavir on risk of hospitalization among patients with COVID-19: the TOGETHER randomized …", "JAMA Network …"),
  },
  {
    id: 15,
    title: "A multi-center, adaptive, randomized, platform trial to evaluate the effect of repurposed medicines in outpatients with early coronavirus disease 2019 (COVID …",
    authors: "G Reis, EASM Silva, DCM Silva, ...",
    year: 2021,
    journal: "Gates Open …",
    imageUrl: "/pdf/thumbnails/Reis-2021-A multi-center, adaptive, randomized.png",
    aiHint: "",
    pdfUrl: "/pdf/Reis-2021-A multi-center, adaptive, randomized.pdf",
    fullTextUrl: "https://gatesopenresearch.org/articles/5-117",
    abstract: "Background: Although vaccines are currently available for coronavirus disease 2019 (COVID-19), there remains a need for an effective and affordable outpatient treatment for …",
    cites: 14,
    citesPerYear: 3.5,
    slug: createSlug("A multi-center, adaptive, randomized, platform trial to evaluate the effect of repurposed medicines in outpatients with early coronavirus disease 2019 (COVID …"),
    tags: extractTags("A multi-center, adaptive, randomized, platform trial to evaluate the effect of repurposed medicines in outpatients with early coronavirus disease 2019 (COVID …", "Gates Open …"),
  },
  {
    id: 16,
    title: "Towards elimination of mother‐to‐child transmission of HIV in Rwanda: a nested case‐control study of risk factors for transmission",
    authors: "E Remera, P Mugwaneza, F Chammartin, ...",
    year: 2021,
    journal: "BMC pregnancy and …",
    imageUrl: "/pdf/thumbnails/Remera-2021-Towards elimination of mother-to-c.png",
    aiHint: "",
    pdfUrl: "/pdf/Remera-2021-Towards elimination of mother-to-c.pdf",
    fullTextUrl: "https://link.springer.com/article/10.1186/s12884-021-03806-5",
    doi: "10.1186/s12884-021-03806-5",
    abstract: "Background Mother-to-child HIV transmission (MTCT) has substantially declined since the scale-up of prevention programs around the world, including Rwanda. To achieve full …",
    cites: 14,
    citesPerYear: 3.5,
    slug: createSlug("Towards elimination of mother‐to‐child transmission of HIV in Rwanda: a nested case‐control study of risk factors for transmission"),
    tags: extractTags("Towards elimination of mother‐to‐child transmission of HIV in Rwanda: a nested case‐control study of risk factors for transmission", "BMC pregnancy and …"),
  },
  {
    id: 17,
    title: "Durability of non-nucleotide reverse transcriptase inhibitor-based first-line ART regimens after 7 years of treatment in rural Uganda: a prospective cohort study",
    authors: "M Nanfuka, JI Forrest, W Zhang, S Okoboi, J Birungi, ...",
    year: 2021,
    journal: "Medicine",
    imageUrl: "/pdf/thumbnails/Nanfuka-2021-Durability of non-nucleotide reve.png",
    aiHint: "",
    pdfUrl: "/pdf/Nanfuka-2021-Durability of non-nucleotide reve.pdf",
    fullTextUrl: "https://journals.lww.com/md-journal/fulltext/2021/05140/Durability_of_non_nucleotide_reverse_transcriptase.26.aspx?context=LatestArticles",
    abstract: "Most antiretroviral therapy (ART) programs in resource-limited settings have historically used non-nucleotide reverse transcriptase inhibitor (NNRTI)-based regimens with limited …",
    cites: 8,
    citesPerYear: 2.0,
    slug: createSlug("Durability of non-nucleotide reverse transcriptase inhibitor-based first-line ART regimens after 7 years of treatment in rural Uganda: a prospective cohort study"),
    tags: extractTags("Durability of non-nucleotide reverse transcriptase inhibitor-based first-line ART regimens after 7 years of treatment in rural Uganda: a prospective cohort study", "Medicine"),
  },
  {
    id: 18,
    title: "A real-time dashboard of clinical trials for COVID-19",
    authors: "K Thorlund, L Dron, J Park, G Hsu, JI Forrest, ...",
    year: 2020,
    journal: "The Lancet Digital …",
    imageUrl: "/pdf/thumbnails/Thorlund-2020-A real-time dashboard of clinica.png",
    aiHint: "",
    pdfUrl: "/pdf/Thorlund-2020-A real-time dashboard of clinica.pdf",
    fullTextUrl: "https://www.thelancet.com/journals/landig/article/PIIS2589-7500(20)30086-8/fulltext",
    abstract: "In response to the global coronavirus disease 2019 (COVID-19) emergency, clinical trial research assessing the efficacy and safety of clinical candidate interventions to treat COVID …",
    cites: 261,
    citesPerYear: 52.2,
    slug: createSlug("A real-time dashboard of clinical trials for COVID-19"),
    tags: extractTags("A real-time dashboard of clinical trials for COVID-19", "The Lancet Digital …"),
  },
  {
    id: 19,
    title: "The rise and fall of hydroxychloroquine for the treatment and prevention of COVID-19",
    authors: "Z Lee, CR Rayner, JI Forrest, ...",
    year: 2020,
    journal: "… American journal of …",
    imageUrl: "/pdf/thumbnails/Lee-2021-The Rise and Fall of Hydroxychloroqui.png",
    aiHint: "",
    pdfUrl: "/pdf/Lee-2021-The Rise and Fall of Hydroxychloroqui.pdf",
    fullTextUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC7790108/",
    abstract: "The efficacy and safety of hydroxychloroquine (HCQ) for the prevention and treatment of COVID-19 has received great attention, and most notably, the enthusiasm for HCQ has been …",
    cites: 38,
    citesPerYear: 7.6,
    slug: createSlug("The rise and fall of hydroxychloroquine for the treatment and prevention of COVID-19"),
    tags: extractTags("The rise and fall of hydroxychloroquine for the treatment and prevention of COVID-19", "… American journal of …"),
  },
  {
    id: 20,
    title: "Early treatment of COVID-19 disease: a missed opportunity",
    authors: "JI Forrest, CR Rayner, JJH Park, EJ Mills",
    year: 2020,
    journal: "Infectious diseases and therapy",
    imageUrl: "/pdf/thumbnails/Forrest-2020-Early Treatment of COVID-19 Disea.png",
    aiHint: "",
    pdfUrl: "/pdf/Forrest-2020-Early Treatment of COVID-19 Disea.pdf",
    fullTextUrl: "https://link.springer.com/article/10.1007/s40121-020-00349-8",
    doi: "10.1007/s40121-020-00349-8",
    abstract: "Antivirals have demonstrated efficacy in treating other infectious diseases in early stages of disease, reducing morbidity, mortality, and the likelihood of onward transmission. At the time …",
    cites: 22,
    citesPerYear: 4.4,
    slug: createSlug("Early treatment of COVID-19 disease: a missed opportunity"),
    tags: extractTags("Early treatment of COVID-19 disease: a missed opportunity", "Infectious diseases and therapy"),
  },
  {
    id: 21,
    title: "Substance use as a mechanism for social inclusion among gay, bisexual, and other men who have sex with men in Vancouver, Canada",
    authors: "B W. Hawkins, HL Armstrong, S Kesselring, ...",
    year: 2019,
    journal: "Substance Use & …",
    imageUrl: "/images/global-health.jpeg",
    aiHint: "",
    pdfUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC7055638/pdf/nihms-1531343.pdf",
    doi: "10.1080/10826084.2019.1621901",
    abstract: "Background: Previous research demonstrates that substance use preferences and social-sexual environments are highly interrelated for gay, bisexual, and other men who have sex …",
    cites: 32,
    citesPerYear: 5.33,
    slug: createSlug("Substance use as a mechanism for social inclusion among gay, bisexual, and other men who have sex with men in Vancouver, Canada"),
    tags: extractTags("Substance use as a mechanism for social inclusion among gay, bisexual, and other men who have sex with men in Vancouver, Canada", "Substance Use & …"),
  },
  {
    id: 22,
    title: "Thinking upstream: the roles of international health and drug policies in public health responses to chemsex",
    authors: "O Stevens, JI Forrest",
    year: 2018,
    journal: "Sexual Health",
    imageUrl: "/pdf/thumbnails/Stevens-2018-Thinking upstream_ the roles of i.png",
    aiHint: "",
    pdfUrl: "/pdf/Stevens-2018-Thinking upstream_ the roles of i.pdf",
    fullTextUrl: "https://www.publish.csiro.au/sh/sh17153",
    abstract: "Chemsex is a growing public health concern in urban centres, and few interventions exist to mitigate the significant sexual, drug-related, and social harms potentially experienced by …",
    cites: 28,
    citesPerYear: 4.0,
    slug: createSlug("Thinking upstream: the roles of international health and drug policies in public health responses to chemsex"),
    tags: extractTags("Thinking upstream: the roles of international health and drug policies in public health responses to chemsex", "Sexual Health"),
  },
  {
    id: 23,
    title: "The role of community health workers and local leaders in reducing attrition among participant in the AIDS indicator survey and HIV incidence in a national …",
    authors: "M Mutagoma, D Sebuhoro, JP Nyemazi, EJ Mills, ...",
    year: 2018,
    journal: "BMC Public Health",
    imageUrl: "/pdf/thumbnails/Mutagoma-2018-The role of community health wor.png",
    aiHint: "",
    pdfUrl: "/pdf/Mutagoma-2018-The role of community health wor.pdf",
    fullTextUrl: "https://link.springer.com/article/10.1186/s12889-018-5243-x",
    doi: "10.1186/s12889-018-5243-x",
    abstract: "Background Retention of participants in longitudinal prospective surveys can challenging for population health researchers. Community health workers (CHWs) may help reduce attrition …",
    cites: 9,
    citesPerYear: 1.29,
    slug: createSlug("The role of community health workers and local leaders in reducing attrition among participant in the AIDS indicator survey and HIV incidence in a national …"),
    tags: extractTags("The role of community health workers and local leaders in reducing attrition among participant in the AIDS indicator survey and HIV incidence in a national …", "BMC Public Health"),
  },
  {
    id: 24,
    title: "Many pathways to ending AIDS by 2030",
    authors: "S Nsanzimana, JI Forrest",
    year: 2018,
    journal: "The Lancet HIV",
    imageUrl: "/pdf/thumbnails/Many pathways to ending AIDS by 2030.png",
    aiHint: "",
    pdfUrl: "/pdf/Many pathways to ending AIDS by 2030.pdf",
    fullTextUrl: "https://www.thelancet.com/journals/lanhiv/article/PIIS2352-3018(18)30131-0/abstract",
    abstract: "The Rukarara River in western Rwanda is the most distant headwater of the Nile, the longest river in the world. Water originating here joins water from thousands of other tributaries to …",
    cites: 1,
    citesPerYear: 0.14,
    slug: createSlug("Many pathways to ending AIDS by 2030"),
    tags: extractTags("Many pathways to ending AIDS by 2030", "The Lancet HIV"),
  },
  {
    id: 25,
    title: "Interventions to improve adherence to antiretroviral therapy: a systematic review and network meta-analysis",
    authors: "S Kanters, JJH Park, K Chan, ME Socias, N Ford, ...",
    year: 2017,
    journal: "The lancet HIV",
    imageUrl: "/images/global-health.jpeg",
    aiHint: "",
    pdfUrl: "https://www.thelancet.com/pdfs/journals/lanhiv/PIIS2352-3018(16)30206-5.pdf",
    abstract: "Background High adherence to antiretroviral therapy is crucial to the success of HIV treatment. We evaluated comparative effectiveness of adherence interventions with the aim …",
    cites: 303,
    citesPerYear: 37.88,
    slug: createSlug("Interventions to improve adherence to antiretroviral therapy: a systematic review and network meta-analysis"),
    tags: extractTags("Interventions to improve adherence to antiretroviral therapy: a systematic review and network meta-analysis", "The lancet HIV"),
  },
  {
    id: 26,
    title: "Association between Internet use and body dissatisfaction among young females: Cross-sectional analysis of the Canadian Community Health Survey",
    authors: "A Carter, JI Forrest, A Kaida",
    year: 2017,
    journal: "Journal of medical Internet research",
    imageUrl: "/pdf/thumbnails/Carter-2017-Association Between Internet Use a.png",
    aiHint: "",
    pdfUrl: "/pdf/Carter-2017-Association Between Internet Use a.pdf",
    fullTextUrl: "https://www.jmir.org/2017/2/e39/",
    abstract: "Background Recent research suggests Internet exposure, including Facebook use, is positively correlated with body dissatisfaction, especially among girls and young women …",
    cites: 58,
    citesPerYear: 7.25,
    slug: createSlug("Association between Internet use and body dissatisfaction among young females: Cross-sectional analysis of the Canadian Community Health Survey"),
    tags: extractTags("Association between Internet use and body dissatisfaction among young females: Cross-sectional analysis of the Canadian Community Health Survey", "Journal of medical Internet research"),
  },
  {
    id: 27,
    title: "An event-level analysis of the interpersonal factors associated with condomless anal sex among gay, bisexual, and other men who have sex with men (MSM) with …",
    authors: "KG Card, NJ Lachowsky, Z Cui, S Shurgold, ...",
    year: 2017,
    journal: "AIDS Education and …",
    imageUrl: "/pdf/thumbnails/Card-2017-An Event-Level Analysis of the Inter.png",
    aiHint: "",
    pdfUrl: "/pdf/Card-2017-An Event-Level Analysis of the Inter.pdf",
    fullTextUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5564309/pdf/nihms889866.pdf",
    doi: "10.1521/aeap.2017.29.2.154",
    abstract: "The interpersonal determinants of condomless anal sex (CAS) within online-initiated sexual relationships remain poorly understood. Therefore, respondent-driven sampling was used to …",
    cites: 31,
    citesPerYear: 3.88,
    slug: createSlug("An event-level analysis of the interpersonal factors associated with condomless anal sex among gay, bisexual, and other men who have sex with men (MSM) with …"),
    tags: extractTags("An event-level analysis of the interpersonal factors associated with condomless anal sex among gay, bisexual, and other men who have sex with men (MSM) with …", "AIDS Education and …"),
  },
  {
    id: 28,
    title: "A latent class analysis of sexual and romantic relationships among HIV-positive and HIV-negative gay and bisexual men in Vancouver",
    authors: "A Carter, N Lachowsky, JI Forrest, Z Cui, ...",
    year: 2017,
    journal: "… Canadian Journal of …",
    imageUrl: "/pdf/thumbnails/Carter-2017-Latent class analysis.png",
    aiHint: "",
    pdfUrl: "/pdf/Carter-2017-Latent class analysis.pdf",
    fullTextUrl: "https://dralliecarter.com/wp-content/uploads/2019/02/Same-gender-loving-men-and-sexual-wellbeing.pdf",
    doi: "10.3138/cjhs.262.A1",
    abstract: "Quantitative studies of gay and bisexual men have often reduced relational experiences to single dimensions and explored linkages with sexual risk behaviours. We sought to …",
    cites: 6,
    citesPerYear: 0.75,
    slug: createSlug("A latent class analysis of sexual and romantic relationships among HIV-positive and HIV-negative gay and bisexual men in Vancouver"),
    tags: extractTags("A latent class analysis of sexual and romantic relationships among HIV-positive and HIV-negative gay and bisexual men in Vancouver", "… Canadian Journal of …"),
  },
  {
    id: 29,
    title: "Comparative efficacy and safety of first-line antiretroviral therapy for the treatment of HIV infection: a systematic review and network meta-analysis",
    authors: "S Kanters, M Vitoria, M Doherty, ME Socias, N Ford, ...",
    year: 2016,
    journal: "The lancet HIV",
    imageUrl: "/images/double-helix.png",
    aiHint: "",
    pdfUrl: "https://www.academia.edu/download/101448852/Comparative_efficacy_and_safety_of_firstline_ART.pdf",
    abstract: "Background New antiretroviral therapy (ART) regimens for HIV could improve clinical outcomes for patients. To inform global guidelines, we aimed to assess the comparative …",
    cites: 257,
    citesPerYear: 28.56,
    slug: createSlug("Comparative efficacy and safety of first-line antiretroviral therapy for the treatment of HIV infection: a systematic review and network meta-analysis"),
    tags: extractTags("Comparative efficacy and safety of first-line antiretroviral therapy for the treatment of HIV infection: a systematic review and network meta-analysis", "The lancet HIV"),
  },
  {
    id: 30,
    title: "Drug resistance mutations after the first 12 months on antiretroviral therapy and determinants of virological failure in Rwanda",
    authors: "JA Ndahimana, DJ Riedel, ...",
    year: 2016,
    journal: "Tropical Medicine & …",
    imageUrl: "/pdf/thumbnails/Ndahimana-2016-Drug resistance mutations after.png",
    aiHint: "",
    pdfUrl: "/pdf/Ndahimana-2016-Drug resistance mutations after.pdf",
    fullTextUrl: "https://onlinelibrary.wiley.com/doi/pdf/10.1111/tmi.12717",
    doi: "10.1111/tmi.12717",
    abstract: "Objective To evaluate HIV drug resistance (HIVDR) and determinants of virological failure in a large cohort of patients receiving first‐line tenofovir‐based antiretroviral therapy (ART) …",
    cites: 62,
    citesPerYear: 6.89,
    slug: createSlug("Drug resistance mutations after the first 12 months on antiretroviral therapy and determinants of virological failure in Rwanda"),
    tags: extractTags("Drug resistance mutations after the first 12 months on antiretroviral therapy and determinants of virological failure in Rwanda", "Tropical Medicine & …"),
  },
  {
    id: 31,
    title: "Including online-recruited seeds: a respondent-driven sample of men who have sex with men",
    authors: "NJ Lachowsky, A Lal, JI Forrest, KG Card, Z Cui, ...",
    year: 2016,
    journal: "Journal of medical …",
    imageUrl: "/pdf/thumbnails/Lachowsky-2016-Including Online-Recruited Seed.png",
    aiHint: "",
    pdfUrl: "/pdf/Lachowsky-2016-Including Online-Recruited Seed.pdf",
    fullTextUrl: "https://www.jmir.org/2016/3/e51/3360",
    abstract: "Background: Technology has changed the way men who have sex with men (MSM) seek sex and socialize, which may impact the implementation of respondent-driven sampling …",
    cites: 57,
    citesPerYear: 6.33,
    slug: createSlug("Including online-recruited seeds: a respondent-driven sample of men who have sex with men"),
    tags: extractTags("Including online-recruited seeds: a respondent-driven sample of men who have sex with men", "Journal of medical …"),
  },
  {
    id: 32,
    title: "Trends and level of control of hypertension among adults attending an ambulatory HIV clinic in Kampala, Uganda: a retrospective study",
    authors: "R Kalyesubula, A Kayongo, FC Semitala, ...",
    year: 2016,
    journal: "BMJ global …",
    imageUrl: "/pdf/thumbnails/Kalyesubula-2016-Trends and level of control o.png",
    aiHint: "",
    pdfUrl: "/pdf/Kalyesubula-2016-Trends and level of control o.pdf",
    fullTextUrl: "https://gh.bmj.com/content/bmjgh/1/3/e000055.full.pdf",
    abstract: "Background With an ageing HIV-positive population, sub-Saharan Africa is now facing a dual epidemic of communicable and non-communicable diseases (NCDs). This study aimed …",
    cites: 51,
    citesPerYear: 5.67,
    slug: createSlug("Trends and level of control of hypertension among adults attending an ambulatory HIV clinic in Kampala, Uganda: a retrospective study"),
    tags: extractTags("Trends and level of control of hypertension among adults attending an ambulatory HIV clinic in Kampala, Uganda: a retrospective study", "BMJ global …"),
  },
  {
    id: 33,
    title: "Exploring the role of sex-seeking apps and websites in the social and sexual lives of gay, bisexual and other men who have sex with men: a cross-sectional study",
    authors: "KG Card, NJ Lachowsky, Z Cui, S Shurgold, ...",
    year: 2016,
    journal: "Sexual …",
    imageUrl: "/pdf/thumbnails/Card-2017-Exploring the role of sex-seeking ap.png",
    aiHint: "",
    pdfUrl: "/pdf/Card-2017-Exploring the role of sex-seeking ap.pdf",
    fullTextUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5572510/pdf/nihms889860.pdf",
    abstract: "Background The objective of this study was to explore the relationship between online sex-seeking, community/social attachment and sexual behaviour. Methods: Respondent-driven …",
    cites: 39,
    citesPerYear: 4.33,
    slug: createSlug("Exploring the role of sex-seeking apps and websites in the social and sexual lives of gay, bisexual and other men who have sex with men: a cross-sectional study"),
    tags: extractTags("Exploring the role of sex-seeking apps and websites in the social and sexual lives of gay, bisexual and other men who have sex with men: a cross-sectional study", "Sexual …"),
  },
  {
    id: 34,
    title: "Factors associated with productive recruiting in a respondent-driven sample of men who have sex with men in Vancouver, Canada",
    authors: "JI Forrest, NJ Lachowsky, A Lal, Z Cui, P Sereda, ...",
    year: 2016,
    journal: "Journal of Urban …",
    imageUrl: "/pdf/thumbnails/Forrest-2016-Factors Associated with Productiv.png",
    aiHint: "",
    pdfUrl: "/pdf/Forrest-2016-Factors Associated with Productiv.pdf",
    fullTextUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4835350/pdf/11524_2016_Article_32.pdf",
    doi: "10.1007/s11524-016-0032-2",
    abstract: "Respondent-driven sampling (RDS) has become a preferred sampling strategy for HIV research and surveillance in many global settings. Methodological investigation into the …",
    cites: 26,
    citesPerYear: 2.89,
    slug: createSlug("Factors associated with productive recruiting in a respondent-driven sample of men who have sex with men in Vancouver, Canada"),
    tags: extractTags("Factors associated with productive recruiting in a respondent-driven sample of men who have sex with men in Vancouver, Canada", "Journal of Urban …"),
  },
  {
    id: 35,
    title: "Associations of rainfall with childhood under-nutrition in Rwanda: an ecological study using the data from Rwanda meteorology agency and the 2010 …",
    authors: "A Mukabutera, JI Forrest, L Nyirazinyoye, ...",
    year: 2016,
    journal: "Asian Journal of …",
    imageUrl: "/pdf/thumbnails/Mukabutera-2016.png",
    aiHint: "",
    pdfUrl: "/pdf/Mukabutera-2016.pdf",
    fullTextUrl: "https://www.researchgate.net/profile/Mukabutera-Assumpta/publication/295858407_Associations_of_Rainfall_with_Childhood_Under-nutrition_in_Rwanda_An_Ecological_Study_using_the_Data_from_Rwanda_Meteorology_Agency_and_the_2010_Demographic_and_Health_Survey/links/56cec1bd08ae4d8d649aa16f/Associations-of-Rainfall-with-Childhood-Under-nutrition-in-Rwanda-An-Ecological-Study-using-the-Data-from-Rwanda-Meteorology-Agency-and-the-2010-Demographic-and-Health-Survey.pdf",
    abstract: "Seasonality of weather and climate can affect many of the complex pathways of nutrition. Methods: Using Rwanda demographic and health survey (RDHS) and precipitation …",
    cites: 9,
    citesPerYear: 1.0,
    slug: createSlug("Associations of rainfall with childhood under-nutrition in Rwanda: an ecological study using the data from Rwanda meteorology agency and the 2010 …"),
    tags: extractTags("Associations of rainfall with childhood under-nutrition in Rwanda: an ecological study using the data from Rwanda meteorology agency and the 2010 …", "Asian Journal of …"),
  },
  {
    id: 36,
    title: "Life expectancy among HIV-positive patients in Rwanda: a retrospective observational cohort study",
    authors: "S Nsanzimana, E Remera, S Kanters, K Chan, ...",
    year: 2015,
    journal: "The Lancet Global …",
    imageUrl: "/pdf/thumbnails/Nsanzimana-2015-Life expectancy among HIV-posi.png",
    aiHint: "",
    pdfUrl: "/pdf/Nsanzimana-2015-Life expectancy among HIV-posi.pdf",
    fullTextUrl: "https://www.thelancet.com/journals/langlo/article/PIIS2214-109X(14)70364-X/fulltext",
    abstract: "Background Rwanda has achieved substantial progress in scaling up of antiretroviral therapy. We aimed to assess the effect of increased access to antiretroviral therapy on life …",
    cites: 144,
    citesPerYear: 14.4,
    slug: createSlug("Life expectancy among HIV-positive patients in Rwanda: a retrospective observational cohort study"),
    tags: extractTags("Life expectancy among HIV-positive patients in Rwanda: a retrospective observational cohort study", "The Lancet Global …"),
  },
  {
    id: 37,
    title: "Mobile health applications for HIV prevention and care in Africa",
    authors: "JI Forrest, M Wiens, S Kanters, ...",
    year: 2015,
    journal: "Current Opinion in …",
    imageUrl: "/pdf/thumbnails/Forrest-2015-Mobile health applications for HI.png",
    aiHint: "",
    pdfUrl: "/pdf/Forrest-2015-Mobile health applications for HI.pdf",
    fullTextUrl: "https://www.academia.edu/download/39976811/Mobile_health_applications_for_HIV_preve20151113-19563-1k2zf6j.pdf",
    abstract: "The potential for m-health in Africa is numerous and should not be limited only to direct patient-care focused applications. Although the use of smart phone technology is on the rise …",
    cites: 82,
    citesPerYear: 8.2,
    slug: createSlug("Mobile health applications for HIV prevention and care in Africa"),
    tags: extractTags("Mobile health applications for HIV prevention and care in Africa", "Current Opinion in …"),
  },
  {
    id: 38,
    title: "HIV care continuum in Rwanda: a cross-sectional analysis of the national programme",
    authors: "S Nsanzimana, S Kanters, E Remera, JI Forrest, ...",
    year: 2015,
    journal: "The lancet HIV",
    imageUrl: "/pdf/thumbnails/Nsanzimana-2015-HIV care continuum in Rwanda_.png",
    aiHint: "",
    pdfUrl: "/pdf/Nsanzimana-2015-HIV care continuum in Rwanda_.pdf",
    fullTextUrl: "https://www.thelancet.com/journals/lanhiv/article/PIIS2352-3018(15)00024-7/abstract",
    abstract: "Background Rwanda has made remarkable progress towards HIV care programme with strong national monitoring and surveillance. Knowledge about the HIV care continuum …",
    cites: 65,
    citesPerYear: 6.5,
    slug: createSlug("HIV care continuum in Rwanda: a cross-sectional analysis of the national programme"),
    tags: extractTags("HIV care continuum in Rwanda: a cross-sectional analysis of the national programme", "The lancet HIV"),
  },
  {
    id: 39,
    title: "Improving health outcomes through concurrent HIV program scale-up and health system development in Rwanda: 20 years of experience",
    authors: "S Nsanzimana, K Prabhu, H McDermott, E Karita, ...",
    year: 2015,
    journal: "BMC medicine",
    imageUrl: "/pdf/thumbnails/Nsanzimana-2015-Improving health outcomes thro.png",
    aiHint: "",
    pdfUrl: "/pdf/Nsanzimana-2015-Improving health outcomes thro.pdf",
    fullTextUrl: "https://link.springer.com/article/10.1186/s12916-015-0443-z",
    doi: "10.1186/s12916-015-0443-z",
    abstract: "The 1994 genocide against the Tutsi destroyed the health system in Rwanda. It is impressive that a small country like Rwanda has advanced its health system to the point of …",
    cites: 60,
    citesPerYear: 6.0,
    slug: createSlug("Improving health outcomes through concurrent HIV program scale-up and health system development in Rwanda: 20 years of experience"),
    tags: extractTags("Improving health outcomes through concurrent HIV program scale-up and health system development in Rwanda: 20 years of experience", "BMC medicine"),
  },
  {
    id: 40,
    title: "Gay and bisexual men's awareness and knowledge of treatment as prevention: findings from the Momentum Health Study in Vancouver, Canada",
    authors: "A Carter, N Lachowsky, A Rich, ...",
    year: 2015,
    journal: "Journal of the …",
    imageUrl: "/images/global-health.jpeg",
    aiHint: "",
    pdfUrl: "https://onlinelibrary.wiley.com/doi/pdfdirect/10.7448/IAS.18.1.20039",
    doi: "10.7448/IAS.18.1.20039",
    abstract: "Introduction Awareness and knowledge of treatment as prevention (TasP) was assessed among HIV‐positive and HIV‐negative gay, bisexual and other men who have sex with men …",
    cites: 49,
    citesPerYear: 4.9,
    slug: createSlug("Gay and bisexual men's awareness and knowledge of treatment as prevention: findings from the Momentum Health Study in Vancouver, Canada"),
    tags: extractTags("Gay and bisexual men's awareness and knowledge of treatment as prevention: findings from the Momentum Health Study in Vancouver, Canada", "Journal of the …"),
  },
  {
    id: 41,
    title: "Effect of baseline CD4 cell count at linkage to HIV care and at initiation of antiretroviral therapy on mortality in HIV-positive adult patients in Rwanda: a nationwide …",
    authors: "S Nsanzimana, E Remera, S Kanters, JI Forrest, ...",
    year: 2015,
    journal: "The lancet HIV",
    imageUrl: "/pdf/thumbnails/Nsanzimana-2015-Effect of baseline CD4 cell co.png",
    aiHint: "",
    pdfUrl: "/pdf/Nsanzimana-2015-Effect of baseline CD4 cell co.pdf",
    fullTextUrl: "https://www.sciencedirect.com/science/article/am/pii/S2352301815001125",
    abstract: "Background Continued debate exists about whether initiation of antiretroviral therapy (ART) in symptom-free patients at higher baseline CD4 cell counts results in important clinical …",
    cites: 23,
    citesPerYear: 2.3,
    slug: createSlug("Effect of baseline CD4 cell count at linkage to HIV care and at initiation of antiretroviral therapy on mortality in HIV-positive adult patients in Rwanda: a nationwide …"),
    tags: extractTags("Effect of baseline CD4 cell count at linkage to HIV care and at initiation of antiretroviral therapy on mortality in HIV-positive adult patients in Rwanda: a nationwide …", "The lancet HIV"),
  },
  {
    id: 42,
    title: "Impact of implementing performance-based financing on childhood malnutrition in Rwanda",
    authors: "A Binagwaho, J Condo, C Wagner, F Ngabo, ...",
    year: 2014,
    journal: "BMC Public Health",
    imageUrl: "/images/earth-1.png",
    aiHint: "",
    pdfUrl: "https://link.springer.com/article/10.1186/1471-2458-14-1132",
    doi: "10.1186/1471-2458-14-1132",
    abstract: "Background Malnutrition remains a serious concern in Rwanda, particularly among children under-5 years. Performance-based financing (PBF), an innovative health systems financing …",
    cites: 39,
    citesPerYear: 3.55,
    slug: createSlug("Impact of implementing performance-based financing on childhood malnutrition in Rwanda"),
    tags: extractTags("Impact of implementing performance-based financing on childhood malnutrition in Rwanda", "BMC Public Health"),
  },
  {
    id: 43,
    title: "Community mapping and respondent-driven sampling of gay and bisexual men's communities in Vancouver, Canada",
    authors: "JI Forrest, B Stevenson, A Rich, ...",
    year: 2014,
    journal: "Culture, health & …",
    imageUrl: "/images/global-health.jpeg",
    aiHint: "",
    pdfUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4127385/pdf/nihms564022.pdf",
    doi: "10.1080/13691058.2014.881551",
    abstract: "Literature suggests formative research is vital for those using respondent-driven sampling (RDS) to study hidden populations of interest. However, few authors have described in detail …",
    cites: 35,
    citesPerYear: 3.18,
    slug: createSlug("Community mapping and respondent-driven sampling of gay and bisexual men's communities in Vancouver, Canada"),
    tags: extractTags("Community mapping and respondent-driven sampling of gay and bisexual men's communities in Vancouver, Canada", "Culture, health & …"),
  },
  {
    id: 44,
    title: "Factors associated with disclosure of HIV status among a cohort of individuals on antiretroviral therapy in British Columbia, Canada",
    authors: "AJ Hirsch Allen, JI Forrest, S Kanters, N O'Brien, ...",
    year: 2014,
    journal: "AIDS and Behavior",
    imageUrl: "/pdf/thumbnails/Hirch-Allen-2014.png",
    aiHint: "",
    pdfUrl: "/pdf/Hirch-Allen-2014.pdf",
    fullTextUrl: "https://link.springer.com/article/10.1007/s10461-013-0623-9",
    doi: "10.1007/s10461-013-0623-9",
    abstract: "We sought to examine the prevalence and correlates of HIV-disclosure among treatment-experienced individuals in British Columbia, Canada. Study participants completed an …",
    cites: 28,
    citesPerYear: 2.55,
    slug: createSlug("Factors associated with disclosure of HIV status among a cohort of individuals on antiretroviral therapy in British Columbia, Canada"),
    tags: extractTags("Factors associated with disclosure of HIV status among a cohort of individuals on antiretroviral therapy in British Columbia, Canada", "AIDS and Behavior"),
  },
  {
    id: 45,
    title: "Significant differences in clinical outcomes between HIV-hepatitis C virus coinfected individuals with and without injection drug use history",
    authors: "A Cescon, K Chan, JM Raboud, AN Burchell, JI Forrest, ...",
    year: 2014,
    journal: "Aids",
    imageUrl: "/pdf/thumbnails/Cescon-2014-Significant differences in clinica.png",
    aiHint: "",
    pdfUrl: "/pdf/Cescon-2014-Significant differences in clinica.pdf",
    fullTextUrl: "https://journals.lww.com/aidsonline/fulltext/2014/01020/significant_differences_in_clinical_outcomes.14.aspx",
    abstract: "Objective: Studies focusing on HIV-hepatitis C virus (HCV) coinfected individuals without a history of IDU are limited. It is plausible that poorer clinical outcomes in HIV-HCV coinfection …",
    cites: 26,
    citesPerYear: 2.36,
    slug: createSlug("Significant differences in clinical outcomes between HIV-hepatitis C virus coinfected individuals with and without injection drug use history"),
    tags: extractTags("Significant differences in clinical outcomes between HIV-hepatitis C virus coinfected individuals with and without injection drug use history", "Aids"),
  },
  {
    id: 46,
    title: "Trends in plasma HIV-RNA suppression and antiretroviral resistance in British Columbia, 1997–2010",
    authors: "A Cescon, S Kanters, CJ Brumme, ...",
    year: 2014,
    journal: "JAIDS Journal of …",
    imageUrl: "/images/double-helix.png",
    aiHint: "",
    pdfUrl: "/pdf/Trends in Plasma HIV-RNA Suppression and Antiretroviral Resistance in British Columbia, 1997–2010.pdf",
    fullTextUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4266465/pdf/nihms-647298.pdf",
    abstract: "Objectives: To examine temporal trends in plasma viral load (pVL) suppression and antiretroviral resistance from 1997 to 2010 in British Columbia (BC), Canada, and determine …",
    cites: 22,
    citesPerYear: 2.0,
    slug: createSlug("Trends in plasma HIV-RNA suppression and antiretroviral resistance in British Columbia, 1997–2010"),
    tags: extractTags("Trends in plasma HIV-RNA suppression and antiretroviral resistance in British Columbia, 1997–2010", "JAIDS Journal of …"),
  },
  {
    id: 47,
    title: "Building clinical trial priorities at the University of Rwanda",
    authors: "J Condo, B Kateera, E Mutimura, F Birungi, ...",
    year: 2014,
    journal: "Trials",
    imageUrl: "/images/earth-1.png",
    aiHint: "",
    pdfUrl: "/pdf/Building clinical trial priorities at the University of Rwanda.pdf",
    fullTextUrl: "https://link.springer.com/article/10.1186/1745-6215-15-467",
    doi: "10.1186/1745-6215-15-467",
    abstract: "After the genocide in Rwanda, the country's healthcare system collapsed. Remarkable gains have since been made by the state to provide greater clinical service capacity and expand …",
    cites: 8,
    citesPerYear: 0.73,
    slug: createSlug("Building clinical trial priorities at the University of Rwanda"),
    tags: extractTags("Building clinical trial priorities at the University of Rwanda", "Trials"),
  },
  {
    id: 48,
    title: "How do you circumcise a nation? The Rwandan case study",
    authors: "V Mutabazi, JI Forrest, N Ford, EJ Mills",
    year: 2014,
    journal: "BMC medicine",
    imageUrl: "/images/earth-1.png",
    aiHint: "",
    pdfUrl: "/pdf/How do you circumcise a nation- The Rwandan case study.pdf",
    fullTextUrl: "https://link.springer.com/article/10.1186/s12916-014-0184-4",
    doi: "10.1186/s12916-014-0184-4",
    abstract: "Voluntary medical male circumcision has been conclusively demonstrated to reduce the lifetime risk of male acquisition of HIV. The strategy has been adopted as a component of a …",
    cites: 7,
    citesPerYear: 0.64,
    slug: createSlug("How do you circumcise a nation? The Rwandan case study"),
    tags: extractTags("How do you circumcise a nation? The Rwandan case study", "BMC medicine"),
  },
  {
    id: 49,
    title: "Identifying self-perceived HIV-related stigma in a population accessing antiretroviral therapy",
    authors: "D Tzemis, JI Forrest, CM Puskas, W Zhang, ...",
    year: 2013,
    journal: "AIDS care",
    imageUrl: "/pdf/thumbnails/Tzemis-2013-Identifying self-perceived HIV-rel.png",
    aiHint: "",
    pdfUrl: "/pdf/Tzemis-2013-Identifying self-perceived HIV-rel.pdf",
    fullTextUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3879041/pdf/nihms-391195.pdf",
    doi: "10.1080/09540121.2012.687809",
    abstract: "This study identifies factors associated with self-perceived HIV-related stigma (stigma) among a cohort of individuals accessing antiretroviral therapy in British Columbia, Canada …",
    cites: 35,
    citesPerYear: 2.92,
    slug: createSlug("Identifying self-perceived HIV-related stigma in a population accessing antiretroviral therapy"),
    tags: extractTags("Identifying self-perceived HIV-related stigma in a population accessing antiretroviral therapy", "AIDS care"),
  },
  {
    id: 50,
    title: "Cohort profile: longitudinal investigations into supportive and ancillary health services",
    authors: "KC Duncan, K Salters, JI Forrest, ...",
    year: 2013,
    journal: "International journal …",
    imageUrl: "/pdf/thumbnails/Duncan-2013-Cohort Profile_ Longitudinal Inves.png",
    aiHint: "",
    pdfUrl: "/pdf/Duncan-2013-Cohort Profile_ Longitudinal Inves.pdf",
    fullTextUrl: "https://academic.oup.com/ije/article/42/4/947/655421",
    abstract: "Abstract The Longitudinal Investigations into Supportive and Ancillary health services (LISA) study is a cohort of people living with HIV/AIDS who have ever accessed anti-retroviral …",
    cites: 20,
    citesPerYear: 1.67,
    slug: createSlug("Cohort profile: longitudinal investigations into supportive and ancillary health services"),
    tags: extractTags("Cohort profile: longitudinal investigations into supportive and ancillary health services", "International journal …"),
  },
  {
    id: 51,
    title: "Validating a shortened depression scale (10 item CES-D) among HIV-positive people in British Columbia, Canada",
    authors: "W Zhang, N O'Brien, JI Forrest, KA Salters, ...",
    year: 2012,
    journal: "PloS one",
    imageUrl: "/images/double-helix.png",
    aiHint: "",
    pdfUrl: "https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0040793",
    abstract: "Objective To establish the reliability and validity of a shortened (10-item) depression scale used among HIV-positive patients enrolled in the Drug Treatment Program in British …",
    cites: 686,
    citesPerYear: 52.77,
    slug: createSlug("Validating a shortened depression scale (10 item CES-D) among HIV-positive people in British Columbia, Canada"),
    tags: extractTags("Validating a shortened depression scale (10 item CES-D) among HIV-positive people in British Columbia, Canada", "PloS one"),
  },
  {
    id: 52,
    title: "Factors predictive of 30-day postoperative mortality in HIV/AIDS patients in the era of highly active antiretroviral therapy",
    authors: "SM Wiseman, JI Forrest, JE Chan, W Zhang, ...",
    year: 2012,
    journal: "Annals of …",
    imageUrl: "/pdf/thumbnails/Wiseman-2012-Factors predictive of 30-day post.png",
    aiHint: "",
    pdfUrl: "/pdf/Wiseman-2012-Factors predictive of 30-day post.pdf",
    fullTextUrl: "https://journals.lww.com/annalsofsurgery/fulltext/2012/07000/factors_predictive_of_30_day_postoperative.24.aspx",
    abstract: "Background: Factors that predict HIV (human immunodeficiency virus)/AIDS patient postoperative mortality have remained poorly defined. Objectives: The primary objective of …",
    cites: 7,
    citesPerYear: 0.54,
    slug: createSlug("Factors predictive of 30-day postoperative mortality in HIV/AIDS patients in the era of highly active antiretroviral therapy"),
    tags: extractTags("Factors predictive of 30-day postoperative mortality in HIV/AIDS patients in the era of highly active antiretroviral therapy", "Annals of …"),
  },
  {
    id: 53,
    title: "Women and vulnerability to HAART non-adherence: a literature review of treatment adherence by gender from 2000 to 2011",
    authors: "CM Puskas, JI Forrest, S Parashar, KA Salters, ...",
    year: 2011,
    journal: "Current HIV/AIDS …",
    imageUrl: "/images/global-health.jpeg",
    aiHint: "",
    pdfUrl: "https://www.academia.edu/download/46146384/s11904-011-0098-020160601-28769-ec06b6.pdf",
    doi: "10.1007/s11904-011-0098-0",
    abstract: "A literature review of original research articles on adherence to antiretroviral therapy (ART) in developed countries, covering January 2000 to June 2011, was conducted to determine if …",
    cites: 211,
    citesPerYear: 15.07,
    slug: createSlug("Women and vulnerability to HAART non-adherence: a literature review of treatment adherence by gender from 2000 to 2011"),
    tags: extractTags("Women and vulnerability to HAART non-adherence: a literature review of treatment adherence by gender from 2000 to 2011", "Current HIV/AIDS …"),
  },
  {
    id: 54,
    title: "Perceptions of HIV and fertility among adolescents in Soweto, South Africa: stigma and social barriers continue to hinder progress",
    authors: "JI Forrest, A Kaida, J Dietrich, CL Miller, RS Hogg, ...",
    year: 2009,
    journal: "AIDS and Behavior",
    imageUrl: "/pdf/thumbnails/Forrest-2009-Adolescents and fertlity.png",
    aiHint: "",
    pdfUrl: "/pdf/Forrest-2009-Adolescents and fertlity.pdf",
    fullTextUrl: "https://link.springer.com/article/10.1007/s10461-009-9552-z",
    doi: "10.1007/s10461-009-9552-z",
    abstract: "The scale up of highly active antiretroviral therapy (HAART) for the treatment of HIV has raised new concerns relating to fertility desires and outcomes. Among these concerns is …",
    cites: 21,
    citesPerYear: 1.31,
    slug: createSlug("Perceptions of HIV and fertility among adolescents in Soweto, South Africa: stigma and social barriers continue to hinder progress"),
    tags: extractTags("Perceptions of HIV and fertility among adolescents in Soweto, South Africa: stigma and social barriers continue to hinder progress", "AIDS and Behavior"),
  },
];
